#-------------------------------
# General Site Settings

title: Zumba By Andre
description: Zumba Fitness Instructor
email: ZumbaByAndre@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: study, url: '#study'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  '<p><strong>Hello! I’m De'Andre, </strong> and I have a passion to spread kindness and a sense of community TO THE WORLD! I am originally from Cleveland, Ohio, and moved to Chicago in early September of 2016 to further my passion for fitness. The reason I joined the Zumba team is because I LOVE to dance and every class lifts our spirits! I really enjoy how the music frees us from our long, busy days. My career objective would be to obtain a challenging position as a Zumba® Fitness Instructor, and become a rhythm specific Zumba Jammer with a focus on Reggaeton. Joining your team would give me the chance to share that love with your community. I’m very excited, and look forward to meeting you!</p>'


skills:
- {name: Zumba, value: '10'}
- {name: Zumba Step, value: '9'}
- {name: Zumba  Kids, value: '10'}
- {name: Zumba Kids Jr, value: '8'}
- {name: Strong by Zumba, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Zumba, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Zumba, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Zumba Step, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Zumba Kids, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Zumba Kids Jr, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Strong by Zumba, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Strong by Zumba, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Zumba Kids Jr, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Study Section

study:
- {avatar: 'face-aaroni.jpg',
  name: 'Jeanne Simpson',
  title: 'Health Nokia',
  quote: '<p><strong>Studies done all over the world link dance to mood improvement</strong> A bulk of research is dedicated to the emotional benefits of dance</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Markham Heid',
  title: 'TIME Health',
  quote: '<p><strong> Research supports the idea that dancing can curb anxiety</strong> Dancing seems to encourage social bonding and what psychologists call “self-other merging”</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stephanie Finn',
  title: 'Registered Nurse, CentreSpring MD',
  quote: '<p><strong>Not only will you be staying flexible, dancing will help tone your muscles, improve heart and lung function</strong> and if you dance enough to work up a sweat you just increased detox potential</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Daniel Tarsy, MD',
  title: 'HMS professor of neurology at BIDMC',
  quote: '<p><strong>Studies show that dance helps reduce stress, increases levels of the feel-good hormone serotonin, and helps develop new neural connections</strong>In a small study undertaken in 2012, researchers at North Dakota’s Minot State University found that the Latin-style dance program known as Zumba improves mood and certain cognitive skills, such as visual recognition and decision-making.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
