#-------------------------------
# General Site Settings

title: Zumba By Andre
description: Zumba Fitness Instructor
email: ZumbaByAndre@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Travis specializes in making things** for human people.
  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.


skills:
- {name: Zumba, value: '10'}
- {name: Zumba Step, value: '9'}
- {name: Zumba  Kids, value: '10'}
- {name: Zumba Kids Jr, value: '8'}
- {name: Strong by Zumba, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Zumba, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Zumba, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Zumba Step, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Zumba Kids, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Zumba Kids Jr, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Strong by Zumba, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Strong by Zumba, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Zumba Kids Jr, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Jeanne Simpson',
  title: 'Health Nokia',
  quote: '<p><strong>Studies done all over the world link dance to mood improvement</strong> A bulk of research is dedicated to the emotional benefits of dance</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Markham Heid',
  title: 'TIME Health',
  quote: '<p><strong> Research supports the idea that dancing can curb anxiety</strong> Dancing seems to encourage social bonding and what psychologists call “self-other merging”</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
